# Author : KingTheGuy hard_to_find

# Syntax highlighting
# -------------------
"attribute"                 = "hot-pink"
"type"                      = "salmon"
"type.builtin"              = "salmon"
# "type.enum.variant        " = "blue"
"tag"                       = "salmon"
"identifier"                = "yellow"
"keyword"                   = "yellow"
"punctuation"               = "periwinkle"
"punctuation.delimiter"     = "salmon"
"constant.character.escape" = "salmon"
"operator"                  = "salmon"
"special"                   = "salmon"
"constructor"               = "hot-pink"
"keyword.directive"         = "wash"
"namespace"                 = "hot-pink"
"variable.other.member"     = { fg = "wash" }
"variable"                  = { fg = "white" }
"constant"                  = { fg = "white" }
"variable.parameter"        = { fg = "white" }
"function"                  = "wash"
"function.macro"            = "wash"
"function.builtin"          = "hot-pink"
# "comment"                   = { fg = "black", bg = "plant3", modifiers = ["bold"]}
# "comment"                   = "plant3"
# "comment"                   = { fg ="periwinkle", bg="#242424"}
# "comment"                   = { fg ="periwinkle"}
# "comment"                   = { fg ="#0d8aff"}
# "comment"                   = { fg ="slate"}
"comment"                   = { fg ="slate",bg="dark-blue"}
# "comment"                   = { fg ="grey"}
# "comment"                   = { fg ="white"}

# "ui.virtual.inlay-hint.type	" = "gray"
"ui.virtual.inlay-hint"     = { fg = "black" ,bg ="salmon", modifiers = ["bold"] }

"variable.builtin"          = "hot-pink"
"constant.builtin"          = "hot-pink"
"string"                    = "purple"
"string.literal"            = "cyan"
"constant.numeric"          = "blue"
# "label"                     = "#59c0dc"
"label"                     = "blue"
"module"                    = "red"

# TODO
"markup.heading" = "wash"
"markup.heading.1" = { fg = "wash", bg = "dark-gray", modifiers = ["bold"]}
"markup.heading.2" = { fg = "wash", bg = "dark-gray", modifiers = ["underlined"]}
"markup.list" = "salmon"
"markup.bold" = { fg = "yellow", modifiers = ["bold"] }
"markup.italic" = { fg = "purple", modifiers = ["italic"] }
"markup.link.url" = { fg = "yellow", modifiers = ["underlined"] }
"markup.link.text" = { fg = "marigold", bg = "dark-gray" }
"markup.quote" = {fg="hot-pink"}
"markup.raw" = {fg="purple"}
# "markup.raw.inline" = "salmon"
# "markup.raw.inline" = "salmon"
# "markup.raw.block" = "salmon"
# "markup.other" = "salmon"

"diff.plus" = "#59dcb7"
"diff.delta" = "#dc7759"
"diff.minus" = "salmon"


# "ui.background" = { bg = "background" }
"ui.background" = {}

"ui.linenr" = { fg = "gray" }
"ui.linenr.selected" = { fg = "yellow" }  # TODO
"ui.statusline" = { fg = "background", bg = "salmon" }
"ui.statusline.inactive" = { fg = "egg", bg = "grey" }
"ui.popup" = { fg="egg",bg = "dark-blue"}
"ui.window" = { fg = "grey" }
"ui.help" = { bg = "background", fg = "white" }

# NOTE: this seems to apply to raw text in a MD file
"ui.text" = { fg = "white" }
"ui.text.focus" = { fg = "white", modifiers= ["bold"] }

"ui.selection" = { bg = "grey", modifiers = ["bold"]}
# "ui.cursor.match" = { fg = "salmon", modifiers = ["reversed"]}
"ui.cursor" = { bg= "yellow", fg = "black"}
"ui.cursor.match" = { fg = "gray", modifiers = ["reversed"]}
"ui.cursorline" = { bg = "dark-blue"}
# "ui.cursorline" = { bg="sage"}
"ui.menu" = { fg = "egg"}
"ui.menu.selected" = { fg = "yellow"}

"ui.virtual.jump-label" = { fg = "hot-pink", modifiers = ["underlined", "bold"] }

"warning" = { fg = "wash"}
"error" = { fg = "red"}
"info" = { fg = "wash"}
"hint" = { fg = "wash"}

# make diagnostic underlined, to distinguish with selection text.
"diagnostic" = { modifiers = ["underlined"] }
# "diagnostic.hint" = { fg = "blue", modifiers = ["dim"] }
"diagnostic.hint" = { fg = "blue"}

"ui.virtual.whitespace" = { fg = "grey"}
"ui.virtual.wrap" = "dark-gray"


[palette]
foreground = "#b7b8b9"
# foreground = "#c8c8c8"
background = "#0c0d0e"
# background = "#121311" #not as dark
#0f0e0e

##BRIGHT
# back = "#17191b"
white = "#FCFDFE"
egg = "#c8c8c8" ##slightly white
yellow = "#dca060"
red = "#e31a1c"
cyan = "#58dad6" ##green with some blue
wash = "#44e3c6" ##blue/green ish
purple = "#9270cc"
periwinkle = "#CCCCFF" ##bright blue/purple
marigold = "#eba832" ##gold/yellow
# hot-pink = "#e91f63"
hot-pink = "#e93363"
# hot-pink = "#ff0068"
# lemon = "#FFF700"
pineapple = "#FEE12B"

##NUTRAL / BLAND
# blue = "#7aa8c8"
# blue = "#1faaf0"
blue = "#39aaf0"
dark-blue = "#17191b"
green = "#5a9e6d"
plant = "#4a855b"
plant2 = "#2a5235"
plant3 = "#3e6348"
salmon = "#c95c49" ## red like
pink = "#ffd7d7"

##DARK
dark-gray = "#242424"
gray = "#737475"
grey = "#2c2d2e"
black = "#0c0d0e"
slate = "#516572" ##blueish dark
sage = "#69796a" ##greenish dark color
