vsync = true

opacity-rule = [
  "95:class_g = 'kitty' && focused",
  "80:class_g = 'kitty' && !focused",
  "60:class_g = 'URxvt' && !focused"
];

shadow = true

blur-background = true

blur:{
	method = "dual-kawase"
	strength=5
};

backend = "glx";