[language-server.typos]
command = "typos-lsp"

[[language]]
name = "svelte"
language-servers = [ "svelteserver", "typos"]

[[language]]
name = "markdown"
# soft-wrap.enable = true
auto-format = true
formatter = { command = 'prettier', args = ["--parser", "markdown"] }
language-servers = [ "marksman" , "typos" ]

[[language]]
name = "bash"
language-servers = [ "bash-language-server", "typos"]

[language-server]
jdtls = { command = "jdtls" }
language-server = { command = "jdtls", args = [
  "-data", "/home/<USER>/.cache/jdtls/workspace"
  ]}

[[language]]
name = "java"
scope = "source.java"
injection-regex = "java"
file-types = ["java", "jav", "pde"]
roots = ["pom.xml", "build.gradle", "build.gradle.kts"]
language-servers = [ "jdtls" ]
indent = { tab-width = 2, unit = "  " }

# [language-server.jdtls]
# command = "jdt-language-server"
# command = "jdtls"
# args = [ 
#   "-configuration", "/home/surv/.cache/jdtls/config",
#   "-data", "/home/surv/.cache/jdtls/workspace",
#   ]

# [[language]]
# name = "java"
# auto-format = true
# scope = "source.java"
# injection-regex = "java"
# file-types = ["java"]
# roots = ["build.xml", "pom.xml", "settings.gradle", "settings.gradle.kts"]
# indent = { tab-width = 2, unit = "\t" }
# language-servers = { command = "/home/boots/STUFF/jdtls/bin/jdtls", timeout = 240, args = [ 
#   "-configuration", "/home/boots/.cache/jdtls/config",
#   "-data", "/home/boots/.cache/jdtls/workspace",
#   ]}
# language-servers = [ {name = "jdtls"} ]


[language-server.godot]
command = "nc" 
args = [ "127.0.0.1", "6005"]

[[language]]
name = "gdscript"
language-servers = [ "godot" ]

# [[language]]
# name = "gdscript"
# scope = "source.gdscript"
# injection-regex = "gdscript"
# file-types = ["gd", "gdscript", "gdscript3", "gdscript4"]
# roots = ["project.godot"]
# auto-format = true
# comment-token = "#"
# indent = { tab-width = 2, unit = "\t" }
# language-servers = [ { command = "nc", args = ["localhost", "6005"] }]

# [language-server.tabnine]
# command = "tabnine"

# [[language]]
# name = "zig"
# language-server = { command = "zls"}

[[language]]
name = "xml"
file-types= ["xml"]
comment-token = "<!--"
# formatter = { command = "xmllint", args = ["--pretty" , "1"] }
formatter = { command = "xmllint", args = ["--format" , "-"] }
auto-format = true

[[language]]
name = "go"
indent = { tab-width = 2, unit = "\t" }

# language-servers = [ "tabnine", "gopls" ]

# [[language]]
# name = "yuck"
# formatter = { command = 'prettier', args = ["--parser", "yaml"] }
# auto-format = true
