#!/usr/bin/env bash
# this is a simple config for herbstluftwm

# NOTE: bottles is not a fan of herbstluftwm atm

hc() {
    herbstclient "$@"
}

hc emit_hook reload

##COLORS##
salmon="#c95c49cc"
yellow="#dca060cc"
wash="#44e3c6cc"
periwinkle="#CCCCFF"
marigold="#eba832"
egg="#c8c8c8"
purple="#9270cc"
black="#0c0d0e"

COLOR=$yellow
COLOR_MISC=$black
COLOR_NONE="#11111100"


xsetroot -solid '#737475' #this is the background color

##AUDIO
pgrep pipewire >/dev/null || pipewire &

##POLKIT
# pgrep -x polkit-mate-aut >/dev/null || /usr/lib/mate-polkit/polkit-mate-authentication-agent-1 &
exec /usr/libexec/polkit-mate-authentication-agent-1 &

# remove all existing keybindings
hc keyunbind --all

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:

hc attr settings.focus_follows_mouse true

hc attr settings.update_dragged_clients true

# sleep 5
# echo ran_output > ran.txt
# xrandr > output.txt
# sleep 2
# pkill herbstluftwm
# exit

herbstclient detect_monitors
##DISPLAY
# ~/.config/herbstluftwm/screen.sh

##WALLPAPPER
# feh --bg-center ~/Pictures/wallpapers/annie-spratt-kxhPtZZLi0k-unsplash.jpg
# feh --bg-fill ~/Pictures/wallpapers/annie-spratt-v6asLq_dYzw-unsplash.jpg
# feh --bg-fill ~/Pictures/wallpapers/annie-spratt-kbl64Hj_K9c-unsplash.jpg
# feh --bg-fill -g +0-1500 ~/Pictures/wallpapers/gabriele-catalano-ioLsN803LWw-unsplash.jpg
# feh --bg-fill Pictures/anime/xenotrip2.avif
feh --bg-fill -g +0-0 Pictures/anime/xenotrip2.avif
# feh --bg-fill -g +0-1100 ~/Pictures/anime/xenotrip20.jpeg
# feh --bg-fill -g +0-1480 ~/Pictures/anime/xenotrip14.jpeg
# feh --bg-fill -g +0-900 ~/Pictures/anime/xenotrip31.jpeg 
# feh --bg-fill -g +0-1200 ~/Pictures/anime/crown.avif
# feh --bg-fill -g +0-800 ~/Pictures/anime/xenotrip23.jpeg
# feh --bg-fill -g +0-0 ~/Pictures/GPIMrQNacAAj9_J.jpeg
# feh --bg-fill -g +0-1800 ~/Pictures/anime/GIEcBJEbsAAjTWG.jpeg

# keybindings
# if you have a super key you will be much happier with Mod set to Mod4
# Mod=Mod1    # Use alt as the main modifier
Mod=Mod4   # Use the super key as the main modifier

TERMINAL=kitty
# TERMINAL=alacritty

hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-q close
# hc keybind $Mod-Shift-q spawn ~/.config/herbstluftwm/kill_program.sh
hc keybind $Mod-Return spawn "${TERMINAL:-alacritty}" # use your $TERMINAL with xterm as fallback

hc keybind XF86AudioRaiseVolume spawn ~/.config/eww/scripts/volume up
hc keybind XF86AudioLowerVolume spawn ~/.config/eww/scripts/volume down
hc keybind XF86AudioMute spawn ~/.config/eww/scripts/volume mute
# hc keybind Ctrl-Shift_R spawn wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle 
hc keybind Ctrl-Shift_R spawn ~/.config/herbstluftwm/micget

hc keybind XF86MonBrightnessUp spawn ~/.config/eww/scripts/light up
hc keybind XF86MonBrightnessDown spawn ~/.config/eww/scripts/light down
# hc keybind XF86MonBrightnessUp-XF86MonBrightnessDown spawn ~/.config/eww/scripts/redshift.sh

hc keybind $Mod-t spawn ~/.config/herbstluftwm/stats.sh
# notify-send "mic muted" -t 1000

# hc keybind $Mod-space spawn dmenu_run
rm .cache/dmenu_run
# hc keybind $Mod-space spawn dmenu_run -fn "Share Tech Mono" -nb "#c95c49" -nf "#c8c8c8" -sf "#0c0d0e" -sb "#c8c8c8" #SALMON
# hc keybind $Mod-space spawn dmenu_run -fn "Share Tech Mono" -nb "#242424" -nf "#c8c8c8" -sf "#0c0d0e" -sb "#44e3c6"  #DARK
hc keybind $Mod-Shift-space spawn rofi -show combi -show-icons -modes combi -combi-modes "window,drun,run" -font "share tech mono 14"
# hc keybind $Mod-Shift-space spawn ~/STUFF/eww/target/release/eww open launcher
# hc keybind $Mod-space spawn ~/.config/herbstluftwm/dmenu_run_hlwm
hc keybind $Mod-space spawn lua ~/.config/eww/lua/open_widget.lua launcher
hc keybind $Mod-e spawn thunar
hc keybind $Mod-Shift_R spawn betterlockscreen -l dimblur

hc keybind $Mod-Shift-f spawn /usr/share/doc/herbstluftwm/examples/maximize.sh

hc keybind $Mod-y spawn ~/.config/herbstluftwm/full_display.sh

# basic movement in tiling and floating mode
# focusing clients
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# moving clients in tiling and floating mode
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-u       split   bottom  0.5
hc keybind $Mod-o       split   right   0.55
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# resizing frames and floating clients
resizestep=0.02
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep

# tags
tag_names=( {1..9} )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if [ -n "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done


# cycle through tags
hc keybind $Mod-bracketright use_index +1 --skip-visible
hc keybind $Mod-bracketleft  use_index -1 --skip-visible

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-Shift-s floating toggle
hc keybind $Mod-s set_attr clients.focus.floating toggle
hc keybind $Mod-Shift-d set_attr clients.focus.decorated toggle
hc keybind $Mod-Shift-m set_attr clients.focus.minimized true
hc keybind $Mod-Control-m jumpto last-minimized
hc keybind $Mod-Shift-p pseudotile toggle
hc keybind $Mod-p spawn $HOME/.config/herbstluftwm/screen_shot.sh
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-m                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
# hc set frame_border_normal_color $COLOR_MISC
hc set frame_border_normal_color $COLOR_NONE
hc set frame_bg_normal_color $COLOR_NONE
hc set frame_border_active_color $COLOR
# hc set frame_bg_normal_color $salmon
hc set frame_bg_active_color $COLOR
hc set frame_border_width 3
hc set show_frame_decorations 'if_empty'
hc set frame_bg_transparent on
hc set frame_transparent_width 0
hc set frame_gap 0

hc attr theme.title_height 15
hc attr theme.title_when never
hc attr theme.title_font 'Share Tech Mono:pixelsize=14'  # example using Xft
# hc attr theme.title_font '-*-fixed-medium-r-*-*-13-*-*-*-*-*-*-*'
hc attr theme.title_depth 3  # space below the title's baseline
hc attr theme.active.color $COLOR
hc attr theme.title_color '#ffffff'
hc attr theme.normal.color '#323232dd'
hc attr theme.urgent.color '#7811A1dd'
hc attr theme.tab_color '#1F1F1Fdd'
hc attr theme.active.tab_color '#2B4F0Add'
hc attr theme.active.tab_outer_color '#6C8257dd'
hc attr theme.active.tab_title_color '#ababab'
hc attr theme.normal.title_color '#898989'
hc attr theme.inner_width 3
hc attr theme.inner_color $COLOR
hc attr theme.border_width 3
hc attr theme.floating.border_width 4
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color $COLOR
hc attr theme.urgent.inner_color '#9A65B0'
hc attr theme.normal.inner_color $COLOR_NONE
# hc attr theme.normal.inner_color $COLOR_MISC
# copy inner color to outer_color
for state in active urgent normal ; do
    hc substitute C theme.${state}.inner_color \
        attr theme.${state}.outer_color C
done
hc attr theme.tiling.outer_width 1
hc attr theme.background_color '#141414'

hc set window_gap 3
hc set frame_padding 0
hc set smart_window_surroundings off
hc set smart_frame_surroundings on
hc set mouse_recenter_gap 0

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
hc rule floatplacement=smart
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
hc rule fixedsize floating=on
# hc rule class=Steam floating=on
# hc rule class=steam floating=on
hc rule class=steamwebhelper floating=on
hc rule class=Bitwarden floating=on
hc rule class=Bottles floating=on
# hc rule windowtype='_NET_WM_WINDOW_TYPE_NORMAL' floating=off

hc set tree_style '╾│ ├└╼─┐'

##ALWAYS OPEN
# pgrep alacritty >/dev/null || alacritty &
##ALWAYS OPEN
# pgrep pavucontrol >/dev/null || pavucontrol &

##BAR
# killall eww
# eww reload
pgrep eww >/dev/null || \
eww open bar --arg gap=6px --arg dist=36px
# eww open main_wallpaper

##PICOM
# pkill picom
pgrep picom >/dev/null || picom &

# unlock, just to be sure
hc unlock
