#!/bin/sh

gsettings set org.gnome.desktop.interface gtk-theme "Juno"
gsettings set org.gnome.desktop.interface icon-theme "Adwaita"
gsettings set org.gnome.desktop.interface cursor-theme "Adwaita"

# exec dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY &

# exec systemctl --user import-environment &

##AUDIO
pgrep pipewire >/dev/null || pipewire &
# alias eww="eww_wayland"

# eval $(gnome-keyring-daemon --start)
# export SSH_AUTH_SOCK

# exec /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec /usr/libexec/polkit-mate-authentication-agent-1 &

# Use the "logo" key as the primary modifier
# mod="Mod1"

##COLORS##                                             

salmon="c95c49"
yellow="dca060"
wash="44e3c6"
periwinkle="CCCCFF"

COLOR=$periwinkle
ALT_COLOR=$salmon

##########

mod="Super"

# TILER="river"
# if [[ "$TILER" eq "river" ]]; then
    #river TILE

    # pkill stacktile
    riverctl map normal $mod H send-layout-cmd rivercarro "main-ratio -0.05"
    riverctl map normal $mod L send-layout-cmd rivercarro "main-ratio +0.05"

    riverctl map normal $mod+Shift H send-layout-cmd rivercarro "main-count +1"
    riverctl map normal $mod+Shift L send-layout-cmd rivercarro "main-count -1"

    # riverctl map normal $mod Up    send-layout-cmd rivercarro "main-location top"
    # riverctl map normal $mod Right send-layout-cmd rivercarro "main-location right"
    # riverctl map normal $mod Down  send-layout-cmd rivercarro "main-location bottom"
    # riverctl map normal $mod Left  send-layout-cmd rivercarro "main-location left"

    # And for monocle
    # riverctl map normal $mod M send-layout-cmd rivercarro "main-location monocle"
    # Cycle through layout
    riverctl map normal $mod M send-layout-cmd rivercarro "main-location-cycle left,monocle"

    pkill rivercarro
    # riverctl default-layout rivercarro
    # riverctl spawn rivercarro
    riverctl output-layout rivercarro

    pgrep rivercarro >/dev/null || exec rivercarro -inner-gaps 6 -outer-gaps 12 -no-smart-gaps -per-tag &

    
#     #stack TILE
#     pkill rivertile
#     # Mod+H and Mod+L to decrease/increase the main ratio of stacktile(1)
#     riverctl map normal $mod+Control H send-layout-cmd stacktile "primary_ratio -0.05"
#     riverctl map normal $mod+Control L send-layout-cmd stacktile "primary_ratio +0.05"

#     # Mod+Shift+H and Mod+Shift+L to increment/decrement the main count of stacktile(1)
#     riverctl map normal $mod+Shift H send-layout-cmd stacktile "primary_count +1"
#     riverctl map normal $mod+Shift L send-layout-cmd stacktile "primary_count -1"

#     riverctl map normal $mod Up    send-layout-cmd stacktile "primary_position top"
#     riverctl map normal $mod Right send-layout-cmd stacktile "primary_position right"
#     riverctl map normal $mod Down  send-layout-cmd stacktile "primary_position bottom"
#     riverctl map normal $mod Left  send-layout-cmd stacktile "primary_position left"

#     riverctl map normal $mod m send-layout-cmd stacktile "primary_sublayout rows,stack,full,dwindle"
#     riverctl map normal $mod+Shift f send-layout-cmd stacktile "all_primary toggle"

#     riverctl default-layout stacktile
#     riverctl attach-mode bottom

#     pkill stacktile
#     pgrep stacktile >/dev/null || exec stacktile --remainder-sublayout stack --per-tag-config &
#     # -view-padding 3 -outer-padding 3 &
# fi


#other
riverctl focus-follows-cursor normal


#set resolution

# wlr-randr --output eDP-1 --off --custom-mode 1600x900@60Hz --pos 0,0 --scale 1
# wlr-randr --output HDMI-A-1 --on --mode 2560x1080@60Hz --pos 1600,0 --scale 1
# wlr-randr --output HDMI-A-1 --custom-mode 2128x900@60Hz --pos 0,0

# wlr-randr --output HDMI-A-1 --on --custom-mode 2128x900@60Hz --pos 1600,0 --scale 1
# wlr-randr --output HDMI-A-1 --on --mode 2560x1080 --pos 0,0 --scale 1


# wlr-randr --output HDMI-A-1 --custom-mode 1707x720@60Hz --pos 0,0

#touchpad
# riverctl input pointer-1739-24385-Synaptics_TM2438-005 tap enabled
# riverctl input pointer-1739-24385-Synaptics_TM2438-005 natural-scroll enabled
riverctl input pointer-5426-285-Synaptics_s32 tap enabled 
riverctl input pointer-5426-285-Synaptics_s32 natural-scroll enabled
riverctl input pointer-5426-285-Synaptics_s3203 tap enabled 
riverctl input pointer-5426-285-Synaptics_s3203 natural-scroll enabled
riverctl input pointer-1386-828-Wacom_Intuos_PT_S_2_Finger natural-scroll enabled

riverctl input pointer-5426-285-Synaptics tap enabled 
riverctl input pointer-5426-285-Synaptics natural-scroll enabled

#lock
# IMAGE=~/Pictures/anime/crown.avif
LOCK_IMAGE="~/.cache/betterlockscreen/current/wall_dimblur.png"
# IMAGE=~/Pictures/anime/GIEcBJEbsAAjTWG.jpeg
# IMAGE=~/Pictures/something.jpeg
# IMAGE=~/Pictures/GPIMrQNacAAj9_J.jpeg
IMAGE=~/Pictures/anime/GIEcBJEbsAAjTWG.jpeg
# riverctl map normal $mod Shift_R spawn "swaylock -i ~/Pictures/wallpapers/annie-spratt-kxhPtZZLi0k-unsplash.jpg"
# riverctl map normal $mod Shift_R spawn "swaylock -i ~/.cache/betterlockscreen/current/wall_dimblur.png"
# riverctl map normal $mod Shift_R spawn "swaylock -i ~/Pictures/anime/xenotrip7.jpeg --indicator-idle-visible --inside-color 24242470 --ring-color c8c8c870 --separator-color 24242410 --line-color 24242410"
# riverctl map normal $mod Shift_R spawn "swaylock -i ~/.cache/betterlockscreen/current/wall_dimblur.png --indicator-idle-visible --inside-color 24242470 --ring-color c8c8c870 --separator-color 24242410 --line-color 24242410"
# riverctl map normal $mod Shift_R spawn "swaylock -i ~/Pictures/anime/crown.avif --indicator-idle-visible --inside-color $ALT_COLOR --ring-color c8c8c800 --separator-color c8c8c800 --line-color $ALT_COLOR"
riverctl map normal $mod Shift_R spawn "swaylock -i $LOCK_IMAGE --indicator-idle-visible --inside-color $ALT_COLOR --ring-color c8c8c800 --separator-color c8c8c800 --line-color $ALT_COLOR"

# pkill swaybg && swaybg -i $IMAGE -m fill &
# pgrep swaybg >/dev/null || swaybg -i $IMAGE -m fill &

# Mod+Shift+Return to start an instance of foot (https://codeberg.org/dnkl/foot)
riverctl map normal $mod Return spawn alacritty
# riverctl map normal $mod Space spawn 'wofi --show drun --allow-images'
riverctl map normal $mod Space spawn 'fuzzel --list-executables-in-path -w 70 -D no -b 111111ff -t c8c8c8ff -s 242424ff -S c8c8c8ff -B 0'
# riverctl map normal $mod Space spawn 'bemenu-run'
# riverctl map normal $mod Space spawn 'rofi -m -4 -show drun -show-icons'

riverctl map normal $mod E spawn thunar
riverctl map normal $mod P spawn 'grim -g "$(slurp)" "$HOME/Pictures/screenshots/$(date +%F_[%R]).png" && notify-send "SCREENSHOT saved"'
riverctl map normal $mod+Shift P spawn  'grim "$HOME/Pictures/screenshots/$(date +%F_[%R]).png" & notify-send "SCREENSHOT saved"'

# zoom
riverctl map normal $mod Tab zoom

# Mod+Q to close the focused view
riverctl map normal $mod Q close

# reload?
riverctl map normal $mod+Shift R spawn "~/.config/river/init"

# Mod+Q to exit river
riverctl map normal $mod+Shift Q exit

# eww stats
riverctl map normal $mod T spawn ~/.config/herbstluftwm/stats.sh

# Mod+J and Mod+K to focus the next/previous view in the layout stack
riverctl map normal $mod H focus-view left
riverctl map normal $mod J focus-view down
riverctl map normal $mod K focus-view up
riverctl map normal $mod L focus-view right
riverctl map normal $mod C focus-view next
# riverctl map normal $mod J focus-view next
# riverctl map normal $mod K focus-view previous

# Mod+Shift+J and Mod+Shift+K to swap the focused view with the next/previous
# view in the layout stack
riverctl map normal $mod+Shift J swap next
riverctl map normal $mod+Shift K swap previous


# Mod+Period and Mod+Comma to focus the next/previous output
riverctl map normal $mod Period focus-output right
riverctl map normal $mod Comma focus-output left

# Mod+Shift+{Period,Comma} to send the focused view to the next/previous output
riverctl map normal $mod+Shift Period send-to-output next
riverctl map normal $mod+Shift Comma send-to-output previous


# The scratchpad will live on an unused tag. Which tags are used depends on your
# config, but rivers default uses the first 9 tags.
scratch_tag=$((1 << 20 ))

# Toggle the scratchpad with Super+P
riverctl map normal Super V toggle-focused-tags ${scratch_tag}

# Send windows to the scratchpad with Super+Shift+P
riverctl map normal Super+Shift V set-view-tags ${scratch_tag}

# Set spawn tagmask to ensure new windows don't have the scratchpad tag unless
# explicitly set.
all_but_scratch_tag=$(( ((1 << 32) - 1) ^ $scratch_tag ))
riverctl spawn-tagmask ${all_but_scratch_tag}


# Mod+Return to bump the focused view to the top of the layout stack, making
# it the new master
# riverctl map normal $mod Return zoom

# Mod+H and Mod+L to decrease/increase the width of the master column by 5%
# riverctl map normal $mod H mod-master-factor -0.05
# riverctl map normal $mod L mod-master-factor +0.05

# Mod+Shift+H and Mod+Shift+L to increment/decrement the number of
# master views in the layout
# riverctl map normal $mod+Shift H mod-master-count +1
# riverctl map normal $mod+Shift L mod-master-count -1

# Mod+Alt+{H,J,K,L} to move views
# riverctl map normal $mod+Mod1 H move left 100
# riverctl map normal $mod+Mod1 J move down 100
# riverctl map normal $mod+Mod1 K move up 100
# riverctl map normal $mod+Mod1 L move right 100

# Mod+Alt+Control+{H,J,K,L} to snap views to screen edges
# riverctl map normal $mod+Mod1+Control H snap left
# riverctl map normal $mod+Mod1+Control J snap down
# riverctl map normal $mod+Mod1+Control K snap up
# riverctl map normal $mod+Mod1+Control L snap right

# Mod+Alt+Shif+{H,J,K,L} to resize views
# riverctl map normal $mod+Mod1+Shift H resize horizontal -100
# riverctl map normal $mod+Mod1+Shift J resize vertical 100
# riverctl map normal $mod+Mod1+Shift K resize vertical -100
# riverctl map normal $mod+Mod1+Shift L resize horizontal 100

# Mod + Left Mouse Button to move views
riverctl map-pointer normal $mod BTN_LEFT move-view

# Mod + Right Mouse Button to resize views
riverctl map-pointer normal $mod BTN_RIGHT resize-view

for i in $(seq 1 9)
do
    tagmask=$((1 << ($i - 1)))

    # Mod+[1-9] to focus tag [0-8]
    riverctl map normal $mod $i set-focused-tags $tagmask

    # Mod+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal $mod+Shift $i set-view-tags $tagmask

    # Mod+Ctrl+[1-9] to toggle focus of tag [0-8]
    riverctl map normal $mod+Control $i toggle-focused-tags $tagmask

    # Mod+Shift+Ctrl+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal $mod+Shift+Control $i toggle-view-tags $tagmask
done

# Mod+0 to focus all tags
# Mod+Shift+0 to tag focused view with all tags
all_tags_mask=$(((1 << 32) - 1))
riverctl map normal $mod 0 set-focused-tags $all_tags_mask
riverctl map normal $mod+Shift 0 set-view-tags $all_tags_mask

# Mod+Space to toggle float
riverctl map normal $mod S toggle-float

# Mod+F to toggle fullscreen
riverctl map normal $mod F toggle-fullscreen

# Mod+{Up,Right,Down,Left} to change master orientation
# riverctl map normal $mod Up layout stacktile top
# riverctl map normal $mod Right layout stacktile right
# riverctl map normal $mod Down layout stacktile down
# riverctl map normal $mod Left layout stacktile left

# Mod+S to change to Full layout
# riverctl map normal $mod T layout full

# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested wayland compositor
riverctl declare-mode passthrough

# Mod+F11 to enter passthrough mode
riverctl map normal $mod F11 enter-mode passthrough

# Mod+F11 to return to normal mode
riverctl map passthrouh $mod F11 enter-mode normal

#volume
riverctl map -repeat normal None XF86AudioRaiseVolume spawn "~/.config/eww/scripts/volume up"
riverctl map -repeat normal None XF86AudioLowerVolume spawn "~/.config/eww/scripts/volume down"
riverctl map normal None XF86AudioMute spawn "~/.config/eww/scripts/volume mute"

# riverctl map -repeat normal None XF86MonBrightnessUp   spawn light -A 5
# riverctl map -repeat normal None XF86MonBrightnessDown spawn light -U 5

#mic toggle
riverctl map normal Control Shift_R spawn ~/.config/herbstluftwm/micget



# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
# for mode in normal locked
# do
#     # Eject the optical drive
#     riverctl map $mode None XF86Eject spawn eject -T

#     # Control pulse audio volume with pamixer (https://github.com/cdemoulins/pamixer)
#     riverctl map $mode None XF86AudioRaiseVolume spawn wpctl set-volume @DEFAULT_AUDIO_SINK@ 3%+
#     riverctl map $mode None XF86AudioLowerVolume spawn wpctl set-volume @DEFAULT_AUDIO_SINK@ 3%-
#     riverctl map $mode None XF86AudioMute         spawn amixer -c 1 -- sset Maser toggle

#     # Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
#     riverctl map $mode None XF86AudioMedia spawn playerctl play-pause
#     riverctl map $mode None XF86AudioPlay  spawn playerctl play-pause
#     riverctl map $mode None XF86AudioPrev  spawn playerctl previous
#     riverctl map $mode None XF86AudioNext  spawn playerctl next

#     # Control screen backlight brighness with light (https://github.com/haikarainen/light)
# done

# Set repeat rate
riverctl set-repeat 45 300
# riverctl set-repeat 35 200

# Set the layout on startup
#riverctl layout stacktile left



# Set app-ids of views which should float
riverctl float-filter-add "float"
riverctl float-filter-add "popup"
# riverctl float-filter-add "null"

# Set app-ids of views which should use client side decorations
riverctl csd-filter-add "gedit"
riverctl rule-add -app-id "firefox" ssd
riverctl rule-add -app-id "vivaldi" ssd
riverctl rule-add -app-id "thunar" ssd
riverctl rule-add -app-id "pavucontrol" ssd
riverctl rule-add -app-id "*" ssd # is this bad?

# Set opacity and fade effect
# riverctl opacity 1.0 0.75 0.0 0.1 20g

riverctl border-width 3
riverctl background-color 0x0b0b0b
# riverctl border-color-focused 0xdca060
riverctl border-color-focused 0x$COLOR
riverctl border-color-unfocused 0x2c2c2c

# killall waybar ; waybar &
# killall swaybg ; swaybg -i ~/Pictures/wallpapers/baptiste-pKK5mGlB-iw-unsplash.jpg -m fill &
# killall swaybg ; swaybg -i ~/Pictures/wallpapers/annie-spratt-4NVwbmTSyPI-unsplash-edit.jpg -m fill &
# killall swaybg ; swaybg -i ~/Pictures/wallpapers/annie-spratt-8lnhLDwtcGo-unsplash.jpg -m fill &
# killall swaybg ; swaybg -i ~/Pictures/wallpapers/daria-shevtsova-57355.jpg -m fill &
# killall swaybg ; swaybg -i ~/Pictures/wallpapers/annie-spratt-v6asLq_dYzw-unsplash.jpg -m fill &
# killall swaybg ; swaybg -i ~/Pictures/wallpapers/annie-spratt-kxhPtZZLi0k-unsplash.jpg -m fill &
# swaybg -i ~/Pictures/wallpapers/annie-spratt-kxhPtZZLi0k-unsplash.jpg -m fill &
# killall swaybg ; swaybg -i ~/Pictures/anime/xenotrip14_crop.png -m fill &
# killall swaybg ; swaybg -i ~/Pictures/anime/crown.avif -m fill &

dunst &
eww open main_bar
eww open main_wallpaper
# eww open bar
# eww open back_window

#this sets the primary display
# xrandr --output XWAYLAND1 --primary
